//
//  FullScreenRouter.swift
//  JodelChallenge
//
//  Created by Apurva Kochar on 4/30/18.
//  Copyright (c) 2018 Jodel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FullScreenDataPassing
{
  var dataStore: FullScreenDataStore? { get }
}

class FullScreenRouter: FullScreenDataPassing
{
  var dataStore: FullScreenDataStore?
  
}
